[project]
name = "guitool-client"
version = "2.0.0"
description = ""
authors = [
    {name = "Sony Semiconductor Solutions Corp"},
]
requires-python = "==3.11.*"

dependencies = [
    "aiohttp==3.9.5",
    "python-dotenv==1.0.1",
    "python-socketio==5.11.3",
    "modlib",
]

[tool.uv.sources]
modlib = { git = "https://github.com/SonySemiconductorSolutions/aitrios-rpi-application-module-library.git", branch = "main" }
